apiVersion: apps/v1
kind: Deployment
metadata:
  name: wxdsb
  labels:
    app: wxdsb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wxdsb
  template:
    metadata:
      labels:
        app: wxdsb
    spec:
      containers:
        - name: wxdsb
          image: wxdsb
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: wxdsb-sec
            - configMapRef:
                name: wxdsb-env
          ports:
            - containerPort: 8080
              protocol: TCP
