apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wxdsb.fullname" . }}
  labels:
    {{- include "wxdsb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wxdsb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wxdsb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wxdsb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.persistenceVolume.enabled }}
      volumes:
        - name: {{ include "wxdsb.fullname" . }}-vol
          persistentVolumeClaim:
            claimName: {{ include "wxdsb.fullname" . }}-pvc
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "wxdsb.fullname" . }}-sec
            - configMapRef:
                name: {{ include "wxdsb.fullname" . }}-env
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /wxdsb
              port: 8080
          readinessProbe:
            httpGet:
              path: /wxdsb
              port: 8080
          volumeMounts:
          {{- if .Values.persistenceVolume.enabled }}
          - name: {{ include "wxdsb.fullname" . }}-vol
            mountPath: {{ .Values.persistenceVolume.mountPath }}
          {{- end }}
          {{- range $claim := .Values.existingClaimVolumes }}
          - name: {{ $claim.name }}
            mountPath: {{ $claim.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
