apiVersion: v1
kind: Service
metadata:
  name: {{ include "wxdsb.fullname" . }}
  labels:
    {{- include "wxdsb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    {{- include "wxdsb.selectorLabels" . | nindent 4 }}
